name: 'Install Dependencies'
description: 'Install project dependencies'

inputs:
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm@10.13.1

    # - name: Get pnpm store path
    #   id: pnpm-store-path
    #   shell: bash
    #   run: |
    #     echo "pnpm store path: $(pnpm store path)"
    #     echo "store-path=$(pnpm store path)" >> $GITHUB_OUTPUT

    # - name: Cache pnpm store and node_modules
    #   id: pnpm-cache
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ${{ steps.pnpm-store-path.outputs.store-path }}
    #       node_modules
    #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
