#!/usr/bin/env sh

# Header section

echo
echo
echo "Pre-commit hook started"
echo
echo "------------------------------------------------------------------"
echo

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)

# Check prettier
echo "Prettier check   ................................................."

if [ -n "$STAGED_FILES" ]; then
    echo "$STAGED_FILES" | xargs pnpm exec prettier --write --ignore-unknown
    if [ $? -ne 0 ]; then
        echo "Prettier failed."
        exit 1
    fi
fi

# Check linter
echo "Linter check     ................................................."

# Filter files for linter
LINTER_FILES=$(echo "$STAGED_FILES" | grep -E '\.(js|jsx|ts|tsx)$' || true)
echo "$LINTER_FILES"
if [ -n "$LINTER_FILES" ]; then
    echo "$LINTER_FILES" | xargs pnpm exec next lint --fix --file
    if [ $? -ne 0 ]; then
        echo "Linter failed."
        exit 1
    fi
fi

echo "------------------------------------------------------------------"
echo
echo "✨ Good to commit ✨"
echo
echo

exit 0
