name: On push main
run-name: 'Code quality checks for main branch'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: on-push-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-code-checks:
    name: '🔍 Run code quality checks'
    uses: nightstem/nightstem-web/.github/workflows/run-code-checks.yml@main
    secrets: inherit
