name: On push main
run-name: On push main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

concurrency:
  group: on-main-push-group-lock
  cancel-in-progress: true

jobs:
  run-code-checks:
    name: Run code checks
    uses: nightstem/nightstem-web/.github/workflows/run-code-checks.yml@main
    secrets: inherit
